### ISSUE TITLE
Name conflict with other security tool

### ISSUE THREAD

**Issue by mboelen** [Orange-Cyberdefense/fenrir-ocd#1]
While reviewing your tool, we saw there is already another tool with the same name. We want to include your tool on our website, but with the conflict in the name we want to ask you to reconsider renaming it.

Other security tool: https://github.com/Neo23x0/Fenrir

**Comment by Orange-Cyberdefense** [comment]
Hello and thank you for submitting an issue !

Unfortunately I can not rename it at the moment as there was a presentation at the Hack in Paris conference a few days ago with the tool's name and github URL.

However, in a not-too-far future, renaming the tool may be possible as I push more features.

Have a nice day :)
Valérian.

**Comment by mboelen** [comment]
Thanks for the quick reply.

To my understanding, you can actually rename a repo name and GitHub will redirect any requests to the old one. We did it with the Lynis project, which we made lowercase and it kept working for us.

At the moment you decide to rename, please let it know. Then we can cover it in the [security tools](https://linuxsecurity.expert/security-tools/) section of our website :)

**Comment by Orange-Cyberdefense** [comment]
I'll give it a try on our repo internally and I'll come back to you as soon as possible ;)

Have a nice day !

**Comment by Orange-Cyberdefense** [comment]
Hello there ! 

A quick update : you are right ! It is possible to have github redirect traffic from the old URL to the new one. I just need to do some kind of internal validations before changing the name but it should be done in a few days :)

Have nice day !
Valérian.

**Comment by mboelen** [comment]
Great. Sure :)

**Comment by Orange-Cyberdefense** [comment]
Hey !

Sorry for the long wait. 
The repo name has finally changed :)

Thanks a lot and have a nice day !
