### ISSUE TITLE
Interface Configuration

### ISSUE THREAD

**Issue by deikl** [Orange-Cyberdefense/fenrir-ocd#12]
sorry for my question, but do i have to configure a bridge interface or something before i start fenrir?

**Comment by Waffle-Wrath** [comment]
Hello,

Nope !  You do not need to set up a bridge interface. Fenrir does it for you with the "create_virtual_tap" command.

**Comment by deikl** [comment]
hi Waffle-Wrath
crazy... i dont get it running, when i create the virtual tab and connect the client and switch to the external interfaces, the supplicant is not able to authenticate... :-(
when i create a bridge interface and set var 8 in /sys/class/net/br0/bridge/group_fwd_mask to forward eap packets, then the supplicant is able to authenticate...

**Comment by kryptognosis** [comment]
Hello,
Never had to configure any bridged interface, so difficult to say why it fails in your case. From testing it I found the following steps to get it running:

To avoid autoconf bugs, remove any previous packages and install these exact versions: 
```
sudo -H -E pip install "cmd2<=0.7.0"
sudo -H -E pip install "scapy<=2.3.2"
```

To run perfectly:

```
sudo python Interface.py
create_virtual_tap
exit
```

-> In another terminal : put all interfaces in PROMISC (including virtual interface FENRIR).
-> .............................. AFTER 30 sec : 

```
sudo python Interface.py
autoconf
run_debug
```

Once we have more time to debug and migrate to Python3, we'll be able to handle any other issues. 
Cheers
