### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PowerPress** [Orange-Cyberdefense/fenrir-ocd#13]
This is awesome tool any updates to it by chance? Do you mind updating the wiki examples on how to use this gem?

**Comment by kryptognosis** [comment]
Updates will come eventually :). Example usage is that once you get it running, you're on the 802.1x network and can scan* and interact with any network services like you normally would from the host running FENRIR. 
*but go easy with the network scanning, this tool's routing is written in Python and can't handle a large number of packets. 

#### Future usage
There is also a Responder module which integrates the interception capabilities of the Responder tool to FENRIR - but it was held back by the original developer and requires debugging for the moment.
