### ISSUE TITLE
Add Python packaging and deploy to PyPI

### ISSUE THREAD

**Issue by 2xyo** [Orange-Cyberdefense/fenrir-ocd#15]
In order to make FENRIR available to Python users, it would be great to make it available on PyPI, the Python Package Index. This would allow users to get the package via pip as

    pip install fenrir

**Comment by kryptognosis** [comment]
It's a good idea, yeah. Priorities right now are : 1. Migrate to Python3, 2. Improve autoconf module, 3. Everything else
