### ISSUE TITLE
Cmd2 for python2 not available anymore ?

### ISSUE THREAD

**Issue by michalgarcarz** [Orange-Cyberdefense/fenrir-ocd#16]
Hello Team,
```
root@test:~/fenrir-ocd# pip install Cmd2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Cmd2
  Using cached https://www.piwheels.org/simple/cmd2/cmd2-0.9.0-py2.py3-none-any.whl
cmd2 requires Python '>=3.4' but the running Python is 2.7.16
```
It looks like cmd2 now requires python3, but when i installed it with pip3 is looks like the rest of fenrir-ocd is not ready for python3 ? any advice ?

For now i am just using:
```
apt-get install python-cmd2
```
And continuing to use everything with python2.

Thanks,

**Comment by kryptognosis** [comment]
Hello,

Thank you for the message. After some searching I found that if you install the old versions of the libraries used by the original FENRIR project, the bugs are gone. 

To avoid autoconf bugs, remove all previous versions of these packages and install them like this :
```
sudo -H -E pip install "cmd2<=0.7.0"
sudo -H -E pip install "scapy<=2.3.2"
```

This will work while waiting for the Python3 migration (almost there).
Cheers
