### ISSUE TITLE
Legitimate host cannot fetch IP adress through DHCP

### ISSUE THREAD

**Issue by Waffle-Wrath** [Orange-Cyberdefense/fenrir-ocd#5]
This is probably due to specific DHCP frames handling (frames without sender IP adress)

The fix should not be too hard to do, probably a new "if" to add in FENRIR2.py

**Comment by allenelson** [comment]
Just found this awesome tool, saving me a ton of time trying to hack things together on my own. Downloaded and running on a kali live image. Debugging my dot1x machine downstairs and can see EAPOL start packets with no response. Adding this in case useful, may be an issue with the default kernel blocking the default address for EAP.. Going to have to debug more tomorrow. Pass through isn't working for me either right now.
