### ISSUE TITLE
Auto-configuration module is bugged

### ISSUE THREAD

**Issue by Waffle-Wrath** [Orange-Cyberdefense/fenrir-ocd#6]
The auto-configuration module integration to the core was incomplete and the module is currently NOT working.

A fix should be coming asap. :)

**Comment by wishbone1138** [comment]
Is autoconf still bugged?  I'm getting a AttributeError when running

**Comment by Waffle-Wrath** [comment]
Hello !

Unfortunately, i do not have time lately to actively debug the autoconf module, so yes it is still bugged.
However, it is possible to manually configure the tool by either using the "set" command or by modifying the source code (top of the main file)

Have a nice day

**Comment by eholmes2io** [comment]
Hey Everyone,

 I've been trying to test this tool lately but I am running into an error that I can't seem to flesh out. Screenshots are below, please let me know if you have any feedback!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2476, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2675, in onecmd
    stop = func(statement)
  File "Interface.py", line 135, in do_set
    if self.FENRIR.setAttribute(args[0], attrValue) == False:
UnboundLocalError: local variable 'attrValue' referenced before assignment
EXCEPTION of type 'UnboundLocalError' occurred with message: 'local variable 'attrValue' referenced before assignment'
To enable full traceback, run the following command:  'set debug true'

**Comment by kryptognosis** [comment]
Hello,

Thank you for the message. After some searching I found that if you install the old versions of the libraries used by the original FENRIR project, the bugs are gone.

To avoid autoconf bugs, remove all previous versions of these packages and install them like this :
```
sudo -H -E pip install "cmd2<=0.7.0"
sudo -H -E pip install "scapy<=2.3.2"
```

This will work while waiting for the Python3 migration (almost there).
Cheers
